// <auto-generated />
namespace OneClick.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class modifyUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201612011620573_modifyUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
